services:
  mariadb:
    image: mariadb:10.11
    container_name: todo-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: your_strong_root_password
      MARIADB_DATABASE: todo
      MARIADB_USER: todo_app_user
      MARIADB_PASSWORD: pw
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mariadb-test:
    image: mariadb:10.11
    container_name: todo-mariadb-test
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: your_strong_root_password
      MARIADB_DATABASE: todo_test
     # MARIADB_USER: root
     # MARIADB_PASSWORD: your_password
    ports:
      - "3308:3306"
    volumes:
      - mariadb_test_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025" 
      - "1025:1025" 
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8025"]
      interval: 1m30s
      timeout: 10s
      retries: 3

volumes:
  mariadb_data:
  mariadb_test_data: