spring.application.name=todo-app
spring.application.api-url=http://localhost:4200/api/v1/
spring.application.url=http://localhost:4200/

spring.messages.basename=messages
spring.messages.encoding=UTF-8


spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://0.0.0.0:3307/todo
spring.datasource.username=${DB_USERNAME:todo_app_user}
spring.datasource.password=${DB_PASSWORD:pw}

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create

# Triggers your OnCreate group just before an SQL INSERT
spring.jpa.properties.jakarta.persistence.validation.group.pre-persist=ibee.webapp.todo_app.validation.idHandle.create.OnCreate

# Triggers your OnUpdate group just before an SQL UPDATE
spring.jpa.properties.jakarta.persistence.validation.group.pre-update=ibee.webapp.todo_app.validation.idHandle.update.OnUpdate

spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret.key=${JWT_SECRET:4de22fc54d5239beb2fc60cf9081ba8838cddea3ec66dcc3e4a242035b1850a31f34dd61d8e26f8f6730eafa198f39651bf50ee89a556b39374be5507ed5036f}
jwt.expiration.time=20000
jwt.refresh.expiration=86400000


spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.auth=false


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false